export const ativos = [
  // =========================
  // AÇÕES IBOVESPA
  // =========================
  "PETR4.SA",
  "VALE3.SA",
  "ITUB4.SA",
  "BBAS3.SA",
  "BBDC4.SA",
  "ABEV3.SA",
  "WEGE3.SA",
  "RENT3.SA",
  "PRIO3.SA",
  "JBSS3.SA",
  "SUZB3.SA",
  "ELET3.SA",
  "ELET6.SA",
  "BPAC11.SA",
  "RAIL3.SA",
  "LREN3.SA",
  "RDOR3.SA",
  "GGBR4.SA",
  "CSNA3.SA",
  "CMIG4.SA",
  "CPLE6.SA",
  "UGPA3.SA",
  "EQTL3.SA",
  "SBSP3.SA",
  "VBBR3.SA",
  "HAPV3.SA",
  "RADL3.SA",
  "B3SA3.SA",
  "EMBR3.SA",
  "KLBN11.SA",
  "BRFS3.SA",
  "CYRE3.SA",
  "MRFG3.SA",
  "TOTS3.SA",
  "CCRO3.SA",
  "ASAI3.SA",
  "GOAU4.SA",
  "MULT3.SA",
  "ENEV3.SA",
  "NTCO3.SA",
  "BRAV3.SA",
  "TIMS3.SA",
  "VIVT3.SA",
  "CPFE3.SA",
  "TAEE11.SA",
  "EGIE3.SA",
  "SANB11.SA",
  "BBSE3.SA",
  "CXSE3.SA",
  "ALOS3.SA",
  "FLRY3.SA",
  "SMTO3.SA",
  "SLCE3.SA",
  "COGN3.SA",
  "CRFB3.SA",
  "AZRE3.SA", // Substituindo PETZ3 (Fusão Arezzo/Petz)
  "YDUQ3.SA",
  "AZUL4.SA",
  "CVCB3.SA",

  // =========================
  // FIIs (Atualizados com Fusões e Base 10)
  // =========================
  "MXRF11.SA",
  "HGLG11.SA",
  "KNRI11.SA",
  "XPLG11.SA",
  "VISC11.SA",
  "XPML11.SA",
  "HSML11.SA",
  "BRCO11.SA",
  "BTLG11.SA", // Recebeu os ativos do BCFF11
  "GGRC11.SA", 
  "CPTS11.SA",
  "PVBI11.SA",
  "RECT11.SA",
  "RZTR11.SA",
  "KNCR11.SA",
  "IRDM11.SA",
  "VGIR11.SA",
  "HCTR11.SA",
  "DEVA11.SA",
  "KNSC11.SA",
  "RECR11.SA",
  "TRXF11.SA",
  "SNCI11.SA",
  "TGAR11.SA",
  "ALZR11.SA",
  "RBRR11.SA",
  "HGRE11.SA",
  "JSRE11.SA",
  "HGBS11.SA",
  "PATL11.SA",
  "LVBI11.SA",
  "RBVA11.SA",
  "VILG11.SA",
  "URPR11.SA",
  "BCRI11.SA",
  "AFHI11.SA",
  "VGIP11.SA",
  "SNFF11.SA",
  "TEPP11.SA",
  "XPCI11.SA",
  "MCCI11.SA",
  "SARE11.SA",
  "HGCR11.SA",
  "OUJP11.SA",
  "GARE11.SA", // Antigo HGLG/Outros de logística que mudaram
  "GALG11.SA", // FII de base 10 muito comum agora
  "VGHF11.SA", // FII base 10 extremamente popular (Opcional)

  // =========================
  // ETFs
  // =========================
  "BOVA11.SA",
  "SMAL11.SA",
  "IVVB11.SA",
  "HASH11.SA",
  "XFIX11.SA",
  "DIVO11.SA",
  "SPXI11.SA",
  "NASD11.SA",
  "QBTC11.SA",
  "QETH11.SA",
  "BOVV11.SA",
  "PIBB11.SA",
  "WRLD11.SA",
  "GOLD11.SA"
];