name: Atualizar Ativos

on:
  schedule:
    - cron: "*/15 13-21 * * 1-5"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Rodar atualização
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: node updateAtivos.js